services:
  server:
    build: .
    ports:
      - "9999:8080"
    env_file:
      - .env
    command: ["--url", "file://../.templates", "--imageUrl", "file://../.images"]
    volumes:
      - forge-templates:/app/.templates
      - forge-images:/app/.images

volumes:
  forge-templates:
  forge-images: